### ISSUE TITLE
Is comparing strings faster than comparing chars over and over?

### ISSUE THREAD

**Issue by jamen** [baggo/palindrome#1]
It's possible we could just slice the string, and do one of two things:

 1. Do reversal on the second half, and compare the halves
 2. Construct a fake palindrome using the first half, and compare against the source

**Comment by whaaaley** [comment]
i think there would be more overhead in reversing half a string than the current implementation of checking one by one and failing early.

there's also complication of the middle character - if there's an odd or even number of characters
